{% set name = "histoprint" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef8b65f7926aaa989f076857b76291175245dd974804b408483091d1e28b00f6

build:
  number: 0
  noarch: python
  entry_points:
    - histoprint=histoprint.cli:histoprint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - toml
  run:
    - click >=7.0.0
    - numpy >=1.0.0
    - python >=3.6

test:
  imports:
    - histoprint
  commands:
    - histoprint --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/histoprint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: histoprint

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
