{% set name = "histoprint" %}
{% set version = "2.6.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1df729350455b457e97f20883537ae74522879e7c33c609df12f247cca4a21d

build:
  number: 0
  noarch: python
  entry_points:
    - histoprint=histoprint.cli:histoprint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - click >=7.0.0
    - numpy >=1.0.0
    - python >={{ python_min }}
    - uhi >=0.2.1

test:
  imports:
    - histoprint
  commands:
    - histoprint --help
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scikit-hep/histoprint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: histoprint
  dev_url: https://github.com/scikit-hep/histoprint

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
